### ISSUE TITLE
Find the case (have ritual object) with the most number of Religious Motifs

### ISSUE THREAD

**Issue by chungyanlee** [Baezhi/DS4_Group-14#1]

**Comment by chungyanlee** [comment]
AccusedRef    CaseRef
A/EGD/2088 | C/EGD/2141

Related to 5 Religious Motifs

**Comment by Baezhi** [comment]
MP/JP/575

**Comment by chungyanlee** [comment]
![image](https://user-images.githubusercontent.com/36131565/100231523-0cca2c80-2f1f-11eb-9db0-061ac8dee2c3.png)

**Comment by LiangJingyin** [comment]
C/EGD/2141 has total 13 ritual objects ( the most)
