### ISSUE TITLE
Find the Case that has the unique ritual object "hand (dead)".

### ISSUE THREAD

**Issue by s-3-ouyang** [Baezhi/DS4_Group-14#11]

**Comment by Baezhi** [comment]
C/JO/3059: This case has all the relationship, and it has UNIQUE RITUAL OBJ "Hand (dead)".

**Comment by Danielagroza** [comment]
"Hand (dead)" and "Rowan tree" are two unique ritual objects associated to this case and also the outliers of the dataset, them not being associated with any other cases.
