### ISSUE TITLE
Find the Case related to the unique ritual object "Mole's feet".

### ISSUE THREAD

**Issue by chungyanlee** [Baezhi/DS4_Group-14#4]

**Comment by Danielagroza** [comment]
witchesData[witchesData.RitualObject_Type.str.contains("Mole's feet", case=False)]

Case C/EGD/59

**Comment by Baezhi** [comment]
C/EGD/59: has the unique ritual obj "mole's feet"

**Comment by LiangJingyin** [comment]
C/EGD/59 here. And what is the specific characteristic of this unique object
